name = "Hugo Initio"
license = "MIT"
licenselink = "https://github.com/miguelsimoni/hugo-initio/blob/master/LICENSE"
description = ""
homepage = "https://miguelsimoni.github.io/hugo-initio-site/"
tags = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
features = ["blog","responsive","personal","google analytics","portfolio","disqus","bootstrap","font awesome","projects","creative","landing page","product","white","share this"]
min_version = "0.1"

[author]
  name = "Miguel Simoni"
  homepage = "https://miguelsimoni.github.io/"

[original]
  name = "Initio"
  author = "Sergey Pozhilov"
  homepage = "http://www.gettemplate.com/info/initio/"
  repo = "https://github.com/pozh/Initio"
